
package Programa;

import JuegoSorteo.vistaPrincipal;
import Restaurante.Cliente;
import Restaurante.Carta;
import Restaurante.TotalesPagar;


public class vistaTotalPagar extends javax.swing.JFrame {
    
   // String varNombre;
   // String varIdentificacion;
    Cliente nuevoCliente = new Cliente();
    String varNombre;
    int varIdentificacion;
    
    
    public vistaTotalPagar(java.awt.Frame parent, boolean modal) {
        initComponents();
        this.setSize(542, 430);
        this.setResizable(false);
        
     /*  String varNombre = "Nombre: "+nuevoCliente.getNombre();
       jLabel10.setText(varNombre); 
       
       String varIdentificacion = "Nombre: "+nuevoCliente.getId();
       jLabel11.setText(varIdentificacion); */
  
     
        
               
        jLabel10.setText("Estimado Sr(a): " + varNombre);
        jLabel11.setText("Con Identificación: " + varIdentificacion);
   
    }

    private vistaTotalPagar() {
        initComponents();       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal = new javax.swing.JLabel();
        jTextTotales = new javax.swing.JTextField();
        jTextValComida = new javax.swing.JTextField();
        btnImprFact = new javax.swing.JButton();
        Registrar1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGenerarFactura = new javax.swing.JButton();
        jTextValPagar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextValBebida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        MenuPrincipal.setFont(new java.awt.Font("Blackadder ITC", 0, 80)); // NOI18N
        MenuPrincipal.setForeground(new java.awt.Color(153, 255, 102));
        MenuPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuPrincipal.setText("Factura");
        getContentPane().add(MenuPrincipal);
        MenuPrincipal.setBounds(150, 0, 240, 80);

        jTextTotales.setEditable(false);
        jTextTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTotalesActionPerformed(evt);
            }
        });
        getContentPane().add(jTextTotales);
        jTextTotales.setBounds(130, 280, 280, 38);

        jTextValComida.setBackground(new java.awt.Color(240, 240, 240));
        jTextValComida.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jTextValComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValComidaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextValComida);
        jTextValComida.setBounds(50, 190, 120, 20);

        btnImprFact.setText("Imprimir Factura");
        btnImprFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprFactActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprFact);
        btnImprFact.setBounds(200, 250, 130, 23);

        Registrar1.setText("Acepto");
        Registrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Registrar1);
        Registrar1.setBounds(137, 370, 80, 23);

        btnSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(310, 370, 60, 23);

        btnGenerarFactura.setBackground(new java.awt.Color(153, 255, 153));
        btnGenerarFactura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGenerarFactura.setText("GENERAR");
        btnGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarFactura);
        btnGenerarFactura.setBounds(210, 140, 110, 23);

        jTextValPagar.setBackground(new java.awt.Color(240, 240, 240));
        jTextValPagar.setBorder(null);
        jTextValPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValPagarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextValPagar);
        jTextValPagar.setBounds(360, 190, 120, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Total a Pagar");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 170, 80, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/satisfechoPng.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(440, 0, 130, 120);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("                                            ");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 80, 270, 20);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("                                            ");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(140, 100, 270, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Da clic en acepto, obtén un número al azar y participa ya por un premio sorpresa!!");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 340, 460, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Valor de Comida");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 170, 100, 20);

        jTextValBebida.setBackground(new java.awt.Color(240, 240, 240));
        jTextValBebida.setBorder(null);
        jTextValBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValBebidaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextValBebida);
        jTextValBebida.setBounds(200, 190, 130, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Valor de Bebida");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 170, 100, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Estamos premiando a todos nuestros clientes por preferirnos. ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 320, 390, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gray-minimalistic-textures-wallpaper-preview (1).jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 540, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTotalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTotalesActionPerformed

    private void jTextValComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValComidaActionPerformed

    private void Registrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registrar1ActionPerformed
            
    vistaPrincipal ventana = new vistaPrincipal();
    ventana.setVisible(false);    
        
        
        
    }//GEN-LAST:event_Registrar1ActionPerformed

    private void jTextValBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValBebidaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnImprFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprFactActionPerformed
  
       jTextTotales.setText("Imprimiendo factura...");
       jTextTotales.setText("Factura impresa con éxito!");
     // TODO add your handling code here:
    }//GEN-LAST:event_btnImprFactActionPerformed

    private void jTextValPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValPagarActionPerformed

    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFacturaActionPerformed
        String texto ="$ " + Carta.getPrecioComida();
        String texto2 ="$ " + Carta.getPrecioBebida();
        String texto3 ="$ " + TotalesPagar.getPrecioTotal();
        // TODO add your handling code here:
        
        jTextValComida.setText(texto);
        jTextValBebida.setText(texto2);
        jTextValPagar.setText(texto3);
    }//GEN-LAST:event_btnGenerarFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaTotalPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaTotalPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaTotalPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaTotalPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaTotalPagar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuPrincipal;
    private javax.swing.JButton Registrar1;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnImprFact;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextTotales;
    private javax.swing.JTextField jTextValBebida;
    private javax.swing.JTextField jTextValComida;
    private javax.swing.JTextField jTextValPagar;
    // End of variables declaration//GEN-END:variables
}
